use UNIVER

--Task 1
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM inner join AUDITORIUM_TYPE on AUDITORIUM_TYPE.[AUDITORIUM_TYPE] = AUDITORIUM.[AUDITORIUM_TYPE]
--Task 2
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM inner join AUDITORIUM_TYPE on AUDITORIUM_TYPE.[AUDITORIUM_TYPE] = AUDITORIUM.[AUDITORIUM_TYPE] and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%'
--Task 3
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM,AUDITORIUM_TYPE where AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME from AUDITORIUM,AUDITORIUM_TYPE where AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%'
-- Task 4

select  STUDENT.NAME as 'Имя студента',FACULTY.FACULTY_NAME as 'Факультет',PROGRESS.SUBJECT as 'Дисциплина', PULPIT.PULPIT as 'Кафедра', PROFESSION.PROFESSION_NAME as 'Специальность', 
case 
when(PROGRESS.NOTE = 6)then 'шесть'
when(PROGRESS.NOTE = 7)then 'семь'
else 'восемь'
end [Оценка]
from STUDENT inner join PROGRESS on STUDENT.IDSTUDENT =  PROGRESS.IDSTUDENT inner join GROUPS on STUDENT.IDGROUP = GROUPS.IDGROUP 
inner join FACULTY on GROUPS.FACULTY = FACULTY.FACULTY inner join SUBJECT on PROGRESS.SUBJECT = SUBJECT.SUBJECT inner join PULPIT on SUBJECT.PULPIT = PULPIT.PULPIT
inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION where PROGRESS.NOTE between 6 and 8
order by FACULTY.FACULTY_NAME,PULPIT.PULPIT,PROFESSION.PROFESSION_NAME,STUDENT.NAME,PROGRESS.NOTE 

--Task 5

select  STUDENT.NAME as 'Имя студента',FACULTY.FACULTY_NAME as 'Факультет',PROGRESS.SUBJECT as 'Дисциплина', PULPIT.PULPIT as 'Кафедра', PROFESSION.PROFESSION_NAME as 'Специальность', 
case 
when(PROGRESS.NOTE = 6)then 'шесть'
when(PROGRESS.NOTE = 7)then 'семь'
else 'восемь'
end [Оценка]
from STUDENT inner join PROGRESS on STUDENT.IDSTUDENT =  PROGRESS.IDSTUDENT inner join GROUPS on STUDENT.IDGROUP = GROUPS.IDGROUP 
inner join FACULTY on GROUPS.FACULTY = FACULTY.FACULTY inner join SUBJECT on PROGRESS.SUBJECT = SUBJECT.SUBJECT inner join PULPIT on SUBJECT.PULPIT = PULPIT.PULPIT
inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION where PROGRESS.NOTE between 6 and 8
order by (
case
when (PROGRESS.NOTE = 6) then 3
when (PROGRESS.NOTE = 8) then 2
else 1
end
)



-- Task 6
select isnull (TEACHER.TEACHER_NAME,'***')[Преподаватель],PULPIT.PULPIT_NAME[Кафедра]
from PULPIT left outer join TEACHER on TEACHER.PULPIT = PULPIT.PULPIT 

-- Task 7
select isnull (TEACHER.TEACHER_NAME,'***')[Преподаватель],PULPIT.PULPIT_NAME[Кафедра]
from TEACHER left outer join PULPIT on TEACHER.PULPIT = PULPIT.PULPIT 

select isnull (TEACHER.TEACHER_NAME,'***')[Преподаватель],PULPIT.PULPIT_NAME[Кафедра]
from TEACHER right outer join PULPIT on TEACHER.PULPIT = PULPIT.PULPIT 

--Task 9

select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
from AUDITORIUM cross join AUDITORIUM_TYPE where AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE






